var dir_baaad8a86a5ce34d1c73a3d19867a3a5 =
[
    [ "compound_file_property.h", "compound__file__property_8h_source.html", null ],
    [ "compound_properties_helper.h", "compound__properties__helper_8h_source.html", null ],
    [ "compound_property_value.h", "compound__property__value_8h_source.html", null ],
    [ "file_constants.h", "file__constants_8h_source.html", null ],
    [ "file_item.h", "file__item_8h_source.html", null ],
    [ "file_item_from_path.h", "file__item__from__path_8h_source.html", null ],
    [ "file_item_from_stream.h", "file__item__from__stream_8h_source.html", null ],
    [ "gsf_input_stream.h", "gsf__input__stream_8h_source.html", null ],
    [ "gsf_output_stream.h", "gsf__output__stream_8h_source.html", null ],
    [ "gsf_types.h", "gsf__types_8h_source.html", null ],
    [ "gsf_utils.h", "gsf__utils_8h_source.html", null ],
    [ "memory_stream.h", "memory__stream_8h_source.html", null ],
    [ "office_constants.h", "office__constants_8h_source.html", null ],
    [ "properties_helper.h", "properties__helper_8h_source.html", null ],
    [ "property_app_version_value.h", "property__app__version__value_8h_source.html", null ],
    [ "property_boolean_value.h", "property__boolean__value_8h_source.html", null ],
    [ "property_date_value.h", "property__date__value_8h_source.html", null ],
    [ "property_number_value.h", "property__number__value_8h_source.html", null ],
    [ "property_string_value.h", "property__string__value_8h_source.html", null ],
    [ "property_time_span_value.h", "property__time__span__value_8h_source.html", null ],
    [ "property_value.h", "property__value_8h_source.html", null ],
    [ "protection_helper.h", "protection__helper_8h_source.html", null ],
    [ "protection_helper_impl.h", "protection__helper__impl_8h_source.html", null ],
    [ "resource_utils.h", "resource__utils_8h_source.html", null ],
    [ "temp_file.h", "temp__file_8h_source.html", null ],
    [ "xml_property.h", "xml__property_8h_source.html", null ]
];