var dir_91db11f6ada6d8175a4dd925b6203276 =
[
    [ "action_constants.h", "action__constants_8h_source.html", null ],
    [ "action_utils.h", "action__utils_8h_source.html", null ],
    [ "add_content_footer_action_impl.h", "add__content__footer__action__impl_8h_source.html", null ],
    [ "add_content_header_action_impl.h", "add__content__header__action__impl_8h_source.html", null ],
    [ "add_dynamic_watermark_action_impl.h", "add__dynamic__watermark__action__impl_8h_source.html", null ],
    [ "add_watermark_action_impl.h", "add__watermark__action__impl_8h_source.html", null ],
    [ "apply_label_action_impl.h", "apply__label__action__impl_8h_source.html", null ],
    [ "content_marking_action_factory.h", "content__marking__action__factory_8h_source.html", null ],
    [ "custom_action_impl.h", "custom__action__impl_8h_source.html", null ],
    [ "justify_action_impl.h", "justify__action__impl_8h_source.html", null ],
    [ "label_action_factory.h", "label__action__factory_8h_source.html", null ],
    [ "metadata_action_impl.h", "metadata__action__impl_8h_source.html", null ],
    [ "protect_action_factory.h", "protect__action__factory_8h_source.html", null ],
    [ "protect_adhoc_action_impl.h", "protect__adhoc__action__impl_8h_source.html", null ],
    [ "protect_adhoc_dk_action_impl.h", "protect__adhoc__dk__action__impl_8h_source.html", null ],
    [ "protect_by_encrypt_only_action_impl.h", "protect__by__encrypt__only__action__impl_8h_source.html", null ],
    [ "protect_by_template_action_impl.h", "protect__by__template__action__impl_8h_source.html", null ],
    [ "protect_do_not_forward_action_impl.h", "protect__do__not__forward__action__impl_8h_source.html", null ],
    [ "protect_do_not_forward_dk_action_impl.h", "protect__do__not__forward__dk__action__impl_8h_source.html", null ],
    [ "recommend_label_action_impl.h", "recommend__label__action__impl_8h_source.html", null ],
    [ "remove_content_footer_action_impl.h", "remove__content__footer__action__impl_8h_source.html", null ],
    [ "remove_content_header_action_impl.h", "remove__content__header__action__impl_8h_source.html", null ],
    [ "remove_dynamic_watermark_action_impl.h", "remove__dynamic__watermark__action__impl_8h_source.html", null ],
    [ "remove_protection_action_impl.h", "remove__protection__action__impl_8h_source.html", null ],
    [ "remove_watermark_action_impl.h", "remove__watermark__action__impl_8h_source.html", null ]
];