var searchData=
[
  ['_5facquire_5fprotector_0',['_acquire_protector',['../structConcurrency_1_1streams_1_1details_1_1__acquire__protector.html',1,'Concurrency::streams::details']]],
  ['_5faescryptcontext_1',['_AESCryptContext',['../struct__AESCryptContext.html',1,'']]],
  ['_5falloc_5fprotector_2',['_alloc_protector',['../structConcurrency_1_1streams_1_1details_1_1__alloc__protector.html',1,'Concurrency::streams::details']]],
  ['_5farray_3',['_Array',['../classweb_1_1json_1_1details_1_1__Array.html',1,'web::json::details']]],
  ['_5fautodeleter_4',['_AutoDeleter',['../structpplx_1_1details_1_1__AutoDeleter.html',1,'pplx::details']]],
  ['_5fbadargtype_5',['_BadArgType',['../structpplx_1_1details_1_1__BadArgType.html',1,'pplx::details']]],
  ['_5fbadcontinuationparamtype_6',['_BadContinuationParamType',['../structpplx_1_1details_1_1__BadContinuationParamType.html',1,'pplx::details']]],
  ['_5fboolean_7',['_Boolean',['../classweb_1_1json_1_1details_1_1__Boolean.html',1,'web::json::details']]],
  ['_5fcancellationtokencallback_8',['_CancellationTokenCallback',['../classpplx_1_1details_1_1__CancellationTokenCallback.html',1,'pplx::details']]],
  ['_5fcancellationtokenregistration_9',['_CancellationTokenRegistration',['../classpplx_1_1details_1_1__CancellationTokenRegistration.html',1,'pplx::details']]],
  ['_5fcancellationtokenstate_10',['_CancellationTokenState',['../classpplx_1_1details_1_1__CancellationTokenState.html',1,'pplx::details']]],
  ['_5fcase_5finsensitive_5fcmp_11',['_case_insensitive_cmp',['../structweb_1_1http_1_1http__headers_1_1__case__insensitive__cmp.html',1,'web::http::http_headers']]],
  ['_5fcompactstring_12',['_CompactString',['../struct__CompactString.html',1,'']]],
  ['_5fcontextcallback_13',['_ContextCallback',['../classpplx_1_1details_1_1__ContextCallback.html',1,'pplx::details']]],
  ['_5fcontinuation_5ffunc_5ftransformer_14',['_Continuation_func_transformer',['../classpplx_1_1__Continuation__func__transformer.html',1,'pplx']]],
  ['_5fcontinuation_5ffunc_5ftransformer_3c_20_5fintype_2c_20void_20_3e_15',['_Continuation_func_transformer&lt; _InType, void &gt;',['../classpplx_1_1__Continuation__func__transformer_3_01__InType_00_01void_01_4.html',1,'pplx']]],
  ['_5fcontinuation_5ffunc_5ftransformer_3c_20void_2c_20_5fouttype_20_3e_16',['_Continuation_func_transformer&lt; void, _OutType &gt;',['../classpplx_1_1__Continuation__func__transformer_3_01void_00_01__OutType_01_4.html',1,'pplx']]],
  ['_5fcontinuation_5ffunc_5ftransformer_3c_20void_2c_20void_20_3e_17',['_Continuation_func_transformer&lt; void, void &gt;',['../classpplx_1_1__Continuation__func__transformer_3_01void_00_01void_01_4.html',1,'pplx']]],
  ['_5fcontinuationtaskhandlebase_18',['_ContinuationTaskHandleBase',['../structpplx_1_1details_1_1__ContinuationTaskHandleBase.html',1,'pplx::details']]],
  ['_5fcontinuationtypetraits_19',['_ContinuationTypeTraits',['../structpplx_1_1details_1_1__ContinuationTypeTraits.html',1,'pplx::details']]],
  ['_5fcopyablefunctor_20',['_CopyableFunctor',['../structpplx_1_1details_1_1__CopyableFunctor.html',1,'pplx::details']]],
  ['_5fcopyablefunctor_3c_20_5fty_2c_20typename_20std_3a_3aenable_5fif_3c_20std_3a_3ais_5fmove_5fconstructible_3c_20_5fty_20_3e_3a_3avalue_20_26_26_21std_3a_3ais_5fcopy_5fconstructible_3c_20_5fty_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e_21',['_CopyableFunctor&lt; _Ty, typename std::enable_if&lt; std::is_move_constructible&lt; _Ty &gt;::value &amp;&amp;!std::is_copy_constructible&lt; _Ty &gt;::value &gt;::type &gt;',['../structpplx_1_1details_1_1__CopyableFunctor_3_01__Ty_00_01typename_01std_1_1enable__if_3_01std_1_6effa22ca2816e74c56983a7fb48c0b4.html',1,'pplx::details']]],
  ['_5fcopyablefunctor_3c_20typenamestd_3a_3adecay_3c_20_5ffunction_20_3e_3a_3atype_20_3e_22',['_CopyableFunctor&lt; typenamestd::decay&lt; _Function &gt;::type &gt;',['../structpplx_1_1details_1_1__CopyableFunctor.html',1,'pplx::details']]],
  ['_5fdouble_5fbyte_23',['_double_byte',['../struct__double__byte.html',1,'']]],
  ['_5fdouble_5fstate_24',['_double_state',['../structConcurrency_1_1streams_1_1__double__state.html',1,'Concurrency::streams']]],
  ['_5fdwordpair_25',['_DWordPair',['../struct__DWordPair.html',1,'']]],
  ['_5fexceptionholder_26',['_ExceptionHolder',['../structpplx_1_1details_1_1__ExceptionHolder.html',1,'pplx::details']]],
  ['_5ffile_5finfo_27',['_file_info',['../structConcurrency_1_1streams_1_1details_1_1__file__info.html',1,'Concurrency::streams::details']]],
  ['_5ffile_5finfo_5fimpl_28',['_file_info_impl',['../structConcurrency_1_1streams_1_1details_1_1__file__info__impl.html',1,'Concurrency::streams::details']]],
  ['_5ffilestream_5fcallback_29',['_filestream_callback',['../classConcurrency_1_1streams_1_1details_1_1__filestream__callback.html',1,'Concurrency::streams::details']]],
  ['_5ffilestream_5fcallback_5ffill_5fbuffer_30',['_filestream_callback_fill_buffer',['../class__filestream__callback__fill__buffer.html',1,'']]],
  ['_5ffunctiontypetraits_31',['_FunctionTypeTraits',['../structpplx_1_1details_1_1__FunctionTypeTraits.html',1,'pplx::details']]],
  ['_5ffunctiontypetraits_3c_20_5ffunction_2c_20void_20_3e_32',['_FunctionTypeTraits&lt; _Function, void &gt;',['../structpplx_1_1details_1_1__FunctionTypeTraits_3_01__Function_00_01void_01_4.html',1,'pplx::details']]],
  ['_5ffx_5fmtrandomcontext_33',['_FX_MTRANDOMCONTEXT',['../struct__FX__MTRANDOMCONTEXT.html',1,'']]],
  ['_5ffx_5fsystemtime_34',['_FX_SYSTEMTIME',['../struct__FX__SYSTEMTIME.html',1,'']]],
  ['_5ffxcrt_5fdatetimezone_35',['_FXCRT_DATETIMEZONE',['../struct__FXCRT__DATETIMEZONE.html',1,'']]],
  ['_5ffxmem_5fsystemmgr_36',['_FXMEM_SystemMgr',['../struct__FXMEM__SystemMgr.html',1,'']]],
  ['_5fgsfinputstream_37',['_GsfInputStream',['../struct__GsfInputStream.html',1,'']]],
  ['_5fgsfoutputstream_38',['_GsfOutputStream',['../struct__GsfOutputStream.html',1,'']]],
  ['_5fguid_39',['_GUID',['../struct__GUID.html',1,'']]],
  ['_5fhttp_5fclient_5fcommunicator_40',['_http_client_communicator',['../classweb_1_1http_1_1client_1_1details_1_1__http__client__communicator.html',1,'web::http::client::details']]],
  ['_5fhttp_5frequest_41',['_http_request',['../classweb_1_1http_1_1details_1_1__http__request.html',1,'web::http::details']]],
  ['_5fhttp_5fresponse_42',['_http_response',['../classweb_1_1http_1_1details_1_1__http__response.html',1,'web::http::details']]],
  ['_5fhttp_5fserver_5fcontext_43',['_http_server_context',['../classweb_1_1http_1_1details_1_1__http__server__context.html',1,'web::http::details']]],
  ['_5finit_5ffunc_5ftransformer_44',['_Init_func_transformer',['../classpplx_1_1__Init__func__transformer.html',1,'pplx']]],
  ['_5finit_5ffunc_5ftransformer_3c_20void_20_3e_45',['_Init_func_transformer&lt; void &gt;',['../classpplx_1_1__Init__func__transformer_3_01void_01_4.html',1,'pplx']]],
  ['_5finitfunctortypetraits_46',['_InitFunctorTypeTraits',['../structpplx_1_1details_1_1__InitFunctorTypeTraits.html',1,'pplx::details']]],
  ['_5finitfunctortypetraits_3c_20t_2c_20t_20_3e_47',['_InitFunctorTypeTraits&lt; T, T &gt;',['../structpplx_1_1details_1_1__InitFunctorTypeTraits_3_01T_00_01T_01_4.html',1,'pplx::details']]],
  ['_5finternal_5ftask_5foptions_48',['_Internal_task_options',['../structpplx_1_1details_1_1__Internal__task__options.html',1,'pplx::details']]],
  ['_5finterruption_5fexception_49',['_Interruption_exception',['../classpplx_1_1details_1_1__Interruption__exception.html',1,'pplx::details']]],
  ['_5fisiasyncinfo_50',['_IsIAsyncInfo',['../structpplx_1_1details_1_1__IsIAsyncInfo.html',1,'pplx::details']]],
  ['_5fisunwrappedasyncselector_51',['_IsUnwrappedAsyncSelector',['../structpplx_1_1details_1_1__IsUnwrappedAsyncSelector.html',1,'pplx::details']]],
  ['_5fisunwrappedasyncselector_3c_20_5ftypeselectornoasync_20_3e_52',['_IsUnwrappedAsyncSelector&lt; _TypeSelectorNoAsync &gt;',['../structpplx_1_1details_1_1__IsUnwrappedAsyncSelector_3_01__TypeSelectorNoAsync_01_4.html',1,'pplx::details']]],
  ['_5fiunknown_5fprotector_53',['_IUnknown_protector',['../structConcurrency_1_1streams_1_1details_1_1__IUnknown__protector.html',1,'Concurrency::streams::details']]],
  ['_5fnoncopyablefunctorwrapper_54',['_NonCopyableFunctorWrapper',['../structpplx_1_1details_1_1__NonCopyableFunctorWrapper.html',1,'pplx::details']]],
  ['_5fnormalizevoidtounittype_55',['_NormalizeVoidToUnitType',['../structpplx_1_1details_1_1__NormalizeVoidToUnitType.html',1,'pplx::details']]],
  ['_5fnormalizevoidtounittype_3c_20void_20_3e_56',['_NormalizeVoidToUnitType&lt; void &gt;',['../structpplx_1_1details_1_1__NormalizeVoidToUnitType_3_01void_01_4.html',1,'pplx::details']]],
  ['_5fnull_57',['_Null',['../classweb_1_1json_1_1details_1_1__Null.html',1,'web::json::details']]],
  ['_5fnumber_58',['_Number',['../classweb_1_1json_1_1details_1_1__Number.html',1,'web::json::details']]],
  ['_5fobject_59',['_Object',['../classweb_1_1json_1_1details_1_1__Object.html',1,'web::json::details']]],
  ['_5fpdfdoc_5fmetadata_60',['_PDFDOC_METADATA',['../struct__PDFDOC__METADATA.html',1,'']]],
  ['_5fppltaskhandle_61',['_PPLTaskHandle',['../structpplx_1_1details_1_1__PPLTaskHandle.html',1,'pplx::details']]],
  ['_5fppltaskhandle_3c_20_5freturntype_2c_20_5finitialtaskhandle_3c_20_5finternalreturntype_2c_20_5ffunction_2c_20_5ftypeselection_20_3e_2c_20details_3a_3a_5funrealizedchore_5ft_20_3e_62',['_PPLTaskHandle&lt; _ReturnType, _InitialTaskHandle&lt; _InternalReturnType, _Function, _TypeSelection &gt;, details::_UnrealizedChore_t &gt;',['../structpplx_1_1details_1_1__PPLTaskHandle.html',1,'pplx::details']]],
  ['_5fppltaskhandle_3c_20details_3a_3a_5fnormalizevoidtounittype_3c_20_5fcontinuationreturntype_20_3e_3a_3a_5ftype_2c_20_5fcontinuationtaskhandle_3c_20_5finternalreturntype_2c_20_5fcontinuationreturntype_2c_20_5ffunction_2c_20_5fistaskbased_2c_20_5ftypeselection_20_3e_2c_20details_3a_3a_5fcontinuationtaskhandlebase_20_3e_63',['_PPLTaskHandle&lt; details::_NormalizeVoidToUnitType&lt; _ContinuationReturnType &gt;::_Type, _ContinuationTaskHandle&lt; _InternalReturnType, _ContinuationReturnType, _Function, _IsTaskBased, _TypeSelection &gt;, details::_ContinuationTaskHandleBase &gt;',['../structpplx_1_1details_1_1__PPLTaskHandle.html',1,'pplx::details']]],
  ['_5frefcounter_64',['_RefCounter',['../classpplx_1_1details_1_1__RefCounter.html',1,'pplx::details']]],
  ['_5fresultholder_65',['_ResultHolder',['../structpplx_1_1details_1_1__ResultHolder.html',1,'pplx::details']]],
  ['_5fresultholder_3c_20_5fresulttype_20_3e_66',['_ResultHolder&lt; _ResultType &gt;',['../structpplx_1_1details_1_1__ResultHolder.html',1,'pplx::details']]],
  ['_5fresultholder_3c_20_5freturntype_20_3e_67',['_ResultHolder&lt; _ReturnType &gt;',['../structpplx_1_1details_1_1__ResultHolder.html',1,'pplx::details']]],
  ['_5fscheduler_5fparam_68',['_Scheduler_Param',['../structpplx_1_1details_1_1__Scheduler__Param.html',1,'pplx::details']]],
  ['_5fsearchtagrecord_69',['_SearchTagRecord',['../struct__SearchTagRecord.html',1,'']]],
  ['_5fsingle_5fbyte_70',['_single_byte',['../struct__single__byte.html',1,'']]],
  ['_5fspin_5flock_71',['_Spin_lock',['../classpplx_1_1details_1_1__Spin__lock.html',1,'pplx::details']]],
  ['_5fstring_72',['_String',['../classweb_1_1json_1_1details_1_1__String.html',1,'web::json::details']]],
  ['_5ftask_5fcompletion_5fevent_5fimpl_73',['_Task_completion_event_impl',['../structpplx_1_1details_1_1__Task__completion__event__impl.html',1,'pplx::details']]],
  ['_5ftask_5fgenerator_5foversubscriber_74',['_Task_generator_oversubscriber',['../structpplx_1_1details_1_1__Task__generator__oversubscriber.html',1,'pplx::details']]],
  ['_5ftask_5fimpl_75',['_Task_impl',['../structpplx_1_1details_1_1__Task__impl.html',1,'pplx::details']]],
  ['_5ftask_5fimpl_5fbase_76',['_Task_impl_base',['../structpplx_1_1details_1_1__Task__impl__base.html',1,'pplx::details']]],
  ['_5ftask_5fptr_77',['_Task_ptr',['../structpplx_1_1details_1_1__Task__ptr.html',1,'pplx::details']]],
  ['_5ftask_5fptr_3c_20details_3a_3a_5fnormalizevoidtounittype_3c_20_5fcontinuationreturntype_20_3e_3a_3a_5ftype_20_3e_78',['_Task_ptr&lt; details::_NormalizeVoidToUnitType&lt; _ContinuationReturnType &gt;::_Type &gt;',['../structpplx_1_1details_1_1__Task__ptr.html',1,'pplx::details']]],
  ['_5ftask_5fptr_3c_20details_3a_3a_5funit_5ftype_20_3e_79',['_Task_ptr&lt; details::_Unit_type &gt;',['../structpplx_1_1details_1_1__Task__ptr.html',1,'pplx::details']]],
  ['_5ftask_5fptr_3c_20successreturntype_20_3e_80',['_Task_ptr&lt; SuccessReturnType &gt;',['../structpplx_1_1details_1_1__Task__ptr.html',1,'pplx::details']]],
  ['_5ftaskcollectionimpl_81',['_TaskCollectionImpl',['../classpplx_1_1details_1_1__TaskCollectionImpl.html',1,'pplx::details']]],
  ['_5ftaskcreationcallstack_82',['_TaskCreationCallstack',['../classpplx_1_1details_1_1__TaskCreationCallstack.html',1,'pplx::details']]],
  ['_5ftaskeventlogger_83',['_TaskEventLogger',['../structpplx_1_1details_1_1__TaskEventLogger.html',1,'pplx::details']]],
  ['_5ftaskprochandle_84',['_TaskProcHandle',['../structpplx_1_1details_1_1__TaskProcHandle.html',1,'pplx::details']]],
  ['_5ftaskprocthunk_85',['_TaskProcThunk',['../structpplx_1_1details_1_1__TaskProcThunk.html',1,'pplx::details']]],
  ['_5ftasktypefromparam_86',['_TaskTypeFromParam',['../structpplx_1_1details_1_1__TaskTypeFromParam.html',1,'pplx::details']]],
  ['_5ftasktypetraits_87',['_TaskTypeTraits',['../structpplx_1_1details_1_1__TaskTypeTraits.html',1,'pplx::details']]],
  ['_5ftasktypetraits_3c_20void_20_3e_88',['_TaskTypeTraits&lt; void &gt;',['../structpplx_1_1details_1_1__TaskTypeTraits_3_01void_01_4.html',1,'pplx::details']]],
  ['_5ftaskworkitemraiilogger_89',['_TaskWorkItemRAIILogger',['../structpplx_1_1details_1_1__TaskWorkItemRAIILogger.html',1,'pplx::details']]],
  ['_5ftriple_5fbyte_90',['_triple_byte',['../struct__triple__byte.html',1,'']]],
  ['_5ftype_5fparser_5fbase_91',['_type_parser_base',['../classConcurrency_1_1streams_1_1__type__parser__base.html',1,'Concurrency::streams']]],
  ['_5ftype_5fparser_5fintegral_5ftraits_92',['_type_parser_integral_traits',['../structConcurrency_1_1streams_1_1__type__parser__integral__traits.html',1,'Concurrency::streams']]],
  ['_5ftypeselectorasyncaction_93',['_TypeSelectorAsyncAction',['../structpplx_1_1details_1_1__TypeSelectorAsyncAction.html',1,'pplx::details']]],
  ['_5ftypeselectorasyncactionwithprogress_94',['_TypeSelectorAsyncActionWithProgress',['../structpplx_1_1details_1_1__TypeSelectorAsyncActionWithProgress.html',1,'pplx::details']]],
  ['_5ftypeselectorasyncoperation_95',['_TypeSelectorAsyncOperation',['../structpplx_1_1details_1_1__TypeSelectorAsyncOperation.html',1,'pplx::details']]],
  ['_5ftypeselectorasyncoperationortask_96',['_TypeSelectorAsyncOperationOrTask',['../structpplx_1_1details_1_1__TypeSelectorAsyncOperationOrTask.html',1,'pplx::details']]],
  ['_5ftypeselectorasyncoperationwithprogress_97',['_TypeSelectorAsyncOperationWithProgress',['../structpplx_1_1details_1_1__TypeSelectorAsyncOperationWithProgress.html',1,'pplx::details']]],
  ['_5ftypeselectorasynctask_98',['_TypeSelectorAsyncTask',['../structpplx_1_1details_1_1__TypeSelectorAsyncTask.html',1,'pplx::details']]],
  ['_5ftypeselectornoasync_99',['_TypeSelectorNoAsync',['../structpplx_1_1details_1_1__TypeSelectorNoAsync.html',1,'pplx::details']]],
  ['_5funwraptasktype_100',['_UnwrapTaskType',['../structpplx_1_1details_1_1__UnwrapTaskType.html',1,'pplx::details']]],
  ['_5funwraptasktype_3c_20task_3c_20_5fty_20_3e_20_3e_101',['_UnwrapTaskType&lt; task&lt; _Ty &gt; &gt;',['../structpplx_1_1details_1_1__UnwrapTaskType_3_01task_3_01__Ty_01_4_01_4.html',1,'pplx::details']]],
  ['_5fvalue_102',['_Value',['../classweb_1_1json_1_1details_1_1__Value.html',1,'web::json::details']]]
];
