var dir_a90912758a95b167421b158f1c77816d =
[
    [ "core", "dir_0292ea60d90e70a5304053f5c7607472.html", "dir_0292ea60d90e70a5304053f5c7607472" ],
    [ "action.h", "action_8h.html", "action_8h" ],
    [ "add_content_footer_action.h", "add__content__footer__action_8h.html", "add__content__footer__action_8h" ],
    [ "add_content_header_action.h", "add__content__header__action_8h.html", "add__content__header__action_8h" ],
    [ "add_dynamic_watermark_action.h", "add__dynamic__watermark__action_8h.html", "add__dynamic__watermark__action_8h" ],
    [ "add_watermark_action.h", "add__watermark__action_8h.html", "add__watermark__action_8h" ],
    [ "apply_label_action.h", "apply__label__action_8h.html", "apply__label__action_8h" ],
    [ "classification_request.h", "classification__request_8h.html", "classification__request_8h" ],
    [ "classification_result.h", "classification__result_8h.html", "classification__result_8h" ],
    [ "content_label.h", "content__label_8h.html", "content__label_8h" ],
    [ "custom_action.h", "custom__action_8h.html", "custom__action_8h" ],
    [ "detailed_classification_result.h", "detailed__classification__result_8h.html", "detailed__classification__result_8h" ],
    [ "execution_state.h", "execution__state_8h.html", "execution__state_8h" ],
    [ "justify_action.h", "justify__action_8h.html", "justify__action_8h" ],
    [ "label.h", "label_8h.html", "label_8h" ],
    [ "metadata_action.h", "metadata__action_8h.html", "metadata__action_8h" ],
    [ "metadata_entry.h", "metadata__entry_8h.html", "metadata__entry_8h" ],
    [ "metadata_version.h", "metadata__version_8h.html", "metadata__version_8h" ],
    [ "policy_engine.h", "policy__engine_8h.html", null ],
    [ "policy_handler.h", "policy__handler_8h.html", "policy__handler_8h" ],
    [ "policy_profile.h", "policy__profile_8h.html", "policy__profile_8h" ],
    [ "protect_adhoc_action.h", "protect__adhoc__action_8h.html", "protect__adhoc__action_8h" ],
    [ "protect_adhoc_dk_action.h", "protect__adhoc__dk__action_8h.html", "protect__adhoc__dk__action_8h" ],
    [ "protect_by_encrypt_only_action.h", "protect__by__encrypt__only__action_8h.html", "protect__by__encrypt__only__action_8h" ],
    [ "protect_by_template_action.h", "protect__by__template__action_8h.html", "protect__by__template__action_8h" ],
    [ "protect_do_not_forward_action.h", "protect__do__not__forward__action_8h.html", "protect__do__not__forward__action_8h" ],
    [ "protect_do_not_forward_dk_action.h", "protect__do__not__forward__dk__action_8h.html", "protect__do__not__forward__dk__action_8h" ],
    [ "recommend_label_action.h", "recommend__label__action_8h.html", "recommend__label__action_8h" ],
    [ "remove_content_footer_action.h", "remove__content__footer__action_8h.html", "remove__content__footer__action_8h" ],
    [ "remove_content_header_action.h", "remove__content__header__action_8h.html", "remove__content__header__action_8h" ],
    [ "remove_dynamic_watermark_action.h", "remove__dynamic__watermark__action_8h.html", "remove__dynamic__watermark__action_8h" ],
    [ "remove_protection_action.h", "remove__protection__action_8h.html", "remove__protection__action_8h" ],
    [ "remove_watermark_action.h", "remove__watermark__action_8h.html", "remove__watermark__action_8h" ],
    [ "sensitivity_types_rule_package.h", "sensitivity__types__rule__package_8h.html", "sensitivity__types__rule__package_8h" ]
];