var hierarchy =
[
    [ "mip::Action", "classmip_1_1Action.html", [
      [ "mip::AddContentFooterAction", "classmip_1_1AddContentFooterAction.html", null ],
      [ "mip::AddContentHeaderAction", "classmip_1_1AddContentHeaderAction.html", null ],
      [ "mip::AddWatermarkAction", "classmip_1_1AddWatermarkAction.html", null ],
      [ "mip::ApplyLabelAction", "classmip_1_1ApplyLabelAction.html", null ],
      [ "mip::CustomAction", "classmip_1_1CustomAction.html", null ],
      [ "mip::JustifyAction", "classmip_1_1JustifyAction.html", null ],
      [ "mip::MetadataAction", "classmip_1_1MetadataAction.html", null ],
      [ "mip::ProtectAdhocAction", "classmip_1_1ProtectAdhocAction.html", null ],
      [ "mip::ProtectAdhocDkAction", "classmip_1_1ProtectAdhocDkAction.html", null ],
      [ "mip::ProtectByTemplateAction", "classmip_1_1ProtectByTemplateAction.html", null ],
      [ "mip::ProtectByTemplateDkAction", "classmip_1_1ProtectByTemplateDkAction.html", null ],
      [ "mip::ProtectDoNotForwardAction", "classmip_1_1ProtectDoNotForwardAction.html", null ],
      [ "mip::ProtectDoNotForwardDkAction", "classmip_1_1ProtectDoNotForwardDkAction.html", null ],
      [ "mip::RecommendLabelAction", "classmip_1_1RecommendLabelAction.html", null ],
      [ "mip::RemoveContentFooterAction", "classmip_1_1RemoveContentFooterAction.html", null ],
      [ "mip::RemoveContentHeaderAction", "classmip_1_1RemoveContentHeaderAction.html", null ],
      [ "mip::RemoveProtectionAction", "classmip_1_1RemoveProtectionAction.html", null ],
      [ "mip::RemoveWatermarkAction", "classmip_1_1RemoveWatermarkAction.html", null ]
    ] ],
    [ "mip::ApplicationInfo", "structmip_1_1ApplicationInfo.html", null ],
    [ "mip::AsyncControl", "classmip_1_1AsyncControl.html", null ],
    [ "mip::AuthDelegate", "classmip_1_1AuthDelegate.html", null ],
    [ "mip::ClassificationRequest", "classmip_1_1ClassificationRequest.html", null ],
    [ "mip::ClassificationResult", "classmip_1_1ClassificationResult.html", null ],
    [ "mip::ConsentDelegate", "classmip_1_1ConsentDelegate.html", null ],
    [ "mip::ProtectionHandler::ConsumptionSettings", "classmip_1_1ProtectionHandler_1_1ConsumptionSettings.html", null ],
    [ "mip::ContentLabel", "classmip_1_1ContentLabel.html", null ],
    [ "std::exception", null, [
      [ "mip::Error", "classmip_1_1Error.html", [
        [ "mip::AccessDeniedError", "classmip_1_1AccessDeniedError.html", [
          [ "mip::NoAuthTokenError", "classmip_1_1NoAuthTokenError.html", null ],
          [ "mip::NoPermissionsError", "classmip_1_1NoPermissionsError.html", null ],
          [ "mip::ServiceDisabledError", "classmip_1_1ServiceDisabledError.html", null ]
        ] ],
        [ "mip::AdhocProtectionRequiredError", "classmip_1_1AdhocProtectionRequiredError.html", null ],
        [ "mip::BadInputError", "classmip_1_1BadInputError.html", [
          [ "mip::InsufficientBufferError", "classmip_1_1InsufficientBufferError.html", null ],
          [ "mip::LabelDisabledError", "classmip_1_1LabelDisabledError.html", null ],
          [ "mip::LabelNotFoundError", "classmip_1_1LabelNotFoundError.html", null ],
          [ "mip::TemplateNotFoundError", "classmip_1_1TemplateNotFoundError.html", null ]
        ] ],
        [ "mip::ConsentDeniedError", "classmip_1_1ConsentDeniedError.html", null ],
        [ "mip::DeprecatedApiError", "classmip_1_1DeprecatedApiError.html", null ],
        [ "mip::FileIOError", "classmip_1_1FileIOError.html", null ],
        [ "mip::InternalError", "classmip_1_1InternalError.html", null ],
        [ "mip::JustificationRequiredError", "classmip_1_1JustificationRequiredError.html", null ],
        [ "mip::NetworkError", "classmip_1_1NetworkError.html", [
          [ "mip::ProxyAuthenticationError", "classmip_1_1ProxyAuthenticationError.html", null ]
        ] ],
        [ "mip::NoPolicyError", "classmip_1_1NoPolicyError.html", null ],
        [ "mip::NotSupportedError", "classmip_1_1NotSupportedError.html", null ],
        [ "mip::OperationCancelledError", "classmip_1_1OperationCancelledError.html", null ],
        [ "mip::PrivilegedRequiredError", "classmip_1_1PrivilegedRequiredError.html", null ]
      ] ]
    ] ],
    [ "mip::ExecutionState", "classmip_1_1ExecutionState.html", null ],
    [ "mip::FileEngine", "classmip_1_1FileEngine.html", null ],
    [ "mip::FileExecutionState", "classmip_1_1FileExecutionState.html", null ],
    [ "mip::FileHandler", "classmip_1_1FileHandler.html", null ],
    [ "mip::FileInspector", "classmip_1_1FileInspector.html", [
      [ "mip::MsgInspector", "classmip_1_1MsgInspector.html", null ]
    ] ],
    [ "mip::FileProfile", "classmip_1_1FileProfile.html", null ],
    [ "mip::HttpDelegate", "classmip_1_1HttpDelegate.html", null ],
    [ "mip::HttpOperation", "classmip_1_1HttpOperation.html", null ],
    [ "mip::HttpRequest", "classmip_1_1HttpRequest.html", null ],
    [ "mip::HttpResponse", "classmip_1_1HttpResponse.html", null ],
    [ "mip::Identity", "classmip_1_1Identity.html", null ],
    [ "mip::Label", "classmip_1_1Label.html", null ],
    [ "mip::LabelingOptions", "classmip_1_1LabelingOptions.html", null ],
    [ "mip::LoggerDelegate", "classmip_1_1LoggerDelegate.html", null ],
    [ "mip::MipContext", "classmip_1_1MipContext.html", null ],
    [ "mip::MsgAttachmentData", "classmip_1_1MsgAttachmentData.html", null ],
    [ "mip::AuthDelegate::OAuth2Challenge", "classmip_1_1AuthDelegate_1_1OAuth2Challenge.html", null ],
    [ "mip::AuthDelegate::OAuth2Token", "classmip_1_1AuthDelegate_1_1OAuth2Token.html", null ],
    [ "mip::FileHandler::Observer", "classmip_1_1FileHandler_1_1Observer.html", null ],
    [ "mip::FileProfile::Observer", "classmip_1_1FileProfile_1_1Observer.html", null ],
    [ "mip::PolicyProfile::Observer", "classmip_1_1PolicyProfile_1_1Observer.html", null ],
    [ "mip::ProtectionEngine::Observer", "classmip_1_1ProtectionEngine_1_1Observer.html", null ],
    [ "mip::ProtectionHandler::Observer", "classmip_1_1ProtectionHandler_1_1Observer.html", null ],
    [ "mip::ProtectionProfile::Observer", "classmip_1_1ProtectionProfile_1_1Observer.html", null ],
    [ "mip::PolicyEngine", "classmip_1_1PolicyEngine.html", null ],
    [ "mip::PolicyHandler", "classmip_1_1PolicyHandler.html", null ],
    [ "mip::PolicyProfile", "classmip_1_1PolicyProfile.html", null ],
    [ "mip::ProtectionDescriptor", "classmip_1_1ProtectionDescriptor.html", null ],
    [ "mip::ProtectionDescriptorBuilder", "classmip_1_1ProtectionDescriptorBuilder.html", null ],
    [ "mip::ProtectionEngine", "classmip_1_1ProtectionEngine.html", null ],
    [ "mip::ProtectionHandler", "classmip_1_1ProtectionHandler.html", null ],
    [ "mip::ProtectionProfile", "classmip_1_1ProtectionProfile.html", null ],
    [ "mip::ProtectionSettings", "classmip_1_1ProtectionSettings.html", null ],
    [ "mip::PublishingLicenseInfo", "classmip_1_1PublishingLicenseInfo.html", null ],
    [ "mip::ProtectionHandler::PublishingSettings", "classmip_1_1ProtectionHandler_1_1PublishingSettings.html", null ],
    [ "mip::SensitivityTypesRulePackage", "classmip_1_1SensitivityTypesRulePackage.html", null ],
    [ "mip::FileEngine::Settings", "classmip_1_1FileEngine_1_1Settings.html", null ],
    [ "mip::FileProfile::Settings", "classmip_1_1FileProfile_1_1Settings.html", null ],
    [ "mip::PolicyEngine::Settings", "classmip_1_1PolicyEngine_1_1Settings.html", null ],
    [ "mip::PolicyProfile::Settings", "classmip_1_1PolicyProfile_1_1Settings.html", null ],
    [ "mip::ProtectionEngine::Settings", "classmip_1_1ProtectionEngine_1_1Settings.html", null ],
    [ "mip::ProtectionProfile::Settings", "classmip_1_1ProtectionProfile_1_1Settings.html", null ],
    [ "mip::Stream", "classmip_1_1Stream.html", null ],
    [ "mip::TaskDispatcherDelegate", "classmip_1_1TaskDispatcherDelegate.html", null ],
    [ "mip::TelemetryConfiguration", "structmip_1_1TelemetryConfiguration.html", null ],
    [ "mip::TemplateDescriptor", "classmip_1_1TemplateDescriptor.html", null ],
    [ "mip::UserRights", "classmip_1_1UserRights.html", null ],
    [ "mip::UserRoles", "classmip_1_1UserRoles.html", null ]
];