MIP SDK for C++: mip::rights Namespace Reference
mip::rights Namespace Reference
Functions
std::string AuditedExtract ()
Gets string identifier for 'audited extract' right.
std::string Comment ()
Gets string identifier for 'comment' right.
std::vector< std::string > CommonRights ()
Gets a list of rights that apply in all scenarios.
std::string Edit ()
Gets string identifier for 'edit' right.
std::vector< std::string > EditableDocumentRights ()
Gets a list of rights that apply to documents.
std::vector< std::string > EmailRights ()
Gets a list of rights that apply to emails.
std::string Export ()
Gets string identifier for 'export' right.
std::string Extract ()
Gets string identifier for 'extract' right.
std::string Forward ()
Gets string identifier for 'forward' right.
std::string Owner ()
Gets string identifier for 'owner' right.
std::string Print ()
Gets string identifier for 'print' right.
std::string Reply ()
Gets string identifier for 'reply' right.
std::string ReplyAll ()
Gets string identifier for 'reply all' right.
std::string View ()
Gets string identifier for 'view' right.
Function Documentation
AuditedExtract()
std::string mip::rights::AuditedExtract () inline
Gets string identifier for 'audited extract' right.
Returns
String identifier for 'audited extract' right
Definition at line 61 of file rights.h.
 { return "AUDITEDEXTRACT"; }
Comment()
std::string mip::rights::Comment () inline
Gets string identifier for 'comment' right.
Returns
String identifier for 'comment' right
Definition at line 96 of file rights.h.
 { return "COMMENT"; }
Referenced by EditableDocumentRights().
CommonRights()
std::vector<std::string> mip::rights::CommonRights () inline
Gets a list of rights that apply in all scenarios.
Returns
A list of rights that apply in all scenarios
Definition at line 142 of file rights.h.
{
   return std::vector<std::string>{Owner(), View()};
 }
References Owner(), and View().
Edit()
std::string mip::rights::Edit () inline
Gets string identifier for 'edit' right.
Returns
String identifier for 'edit' right
Definition at line 68 of file rights.h.
 { return "EDIT"; }
Referenced by EditableDocumentRights().
EditableDocumentRights()
std::vector<std::string> mip::rights::EditableDocumentRights () inline
Gets a list of rights that apply to documents.
Returns
A list of rights that apply to documents
Definition at line 133 of file rights.h.
{
   return std::vector<std::string>{Comment(), Edit(), Extract(), Owner(), Print(), View()};
 }
References Comment(), Edit(), Extract(), Owner(), Print(), and View().
EmailRights()
std::vector<std::string> mip::rights::EmailRights () inline
Gets a list of rights that apply to emails.
Returns
A list of rights that apply to emails
Definition at line 124 of file rights.h.
{
   return std::vector<std::string>{Extract(), Forward(), Owner(), Print(), Reply(), ReplyAll(), View()};
 }
References Extract(), Forward(), Owner(), Print(), Reply(), ReplyAll(), and View().
Export()
std::string mip::rights::Export () inline
Gets string identifier for 'export' right.
Returns
String identifier for 'export' right
Definition at line 75 of file rights.h.
 { return "EXPORT"; }
Extract()
std::string mip::rights::Extract () inline
Gets string identifier for 'extract' right.
Returns
String identifier for 'extract' right
Definition at line 82 of file rights.h.
 { return "EXTRACT"; }
Referenced by EditableDocumentRights(), and EmailRights().
Forward()
std::string mip::rights::Forward () inline
Gets string identifier for 'forward' right.
Returns
String identifier for 'forward' right
Definition at line 117 of file rights.h.
 { return "FORWARD"; }
Referenced by EmailRights().
Owner()
std::string mip::rights::Owner () inline
Gets string identifier for 'owner' right.
Returns
String identifier for 'owner' right
Definition at line 47 of file rights.h.
 { return "OWNER"; }
Referenced by CommonRights(), EditableDocumentRights(), and EmailRights().
Print()
std::string mip::rights::Print () inline
Gets string identifier for 'print' right.
Returns
String identifier for 'print' right
Definition at line 89 of file rights.h.
 { return "PRINT"; }
Referenced by EditableDocumentRights(), and EmailRights().
Reply()
std::string mip::rights::Reply () inline
Gets string identifier for 'reply' right.
Returns
String identifier for 'reply' right
Definition at line 103 of file rights.h.
 { return "REPLY"; }
Referenced by EmailRights().
ReplyAll()
std::string mip::rights::ReplyAll () inline
Gets string identifier for 'reply all' right.
Returns
String identifier for 'reply all' right
Definition at line 110 of file rights.h.
 { return "REPLYALL"; }
Referenced by EmailRights().
View()
std::string mip::rights::View () inline
Gets string identifier for 'view' right.
Returns
String identifier for 'view' right
Definition at line 54 of file rights.h.
 { return "VIEW"; }
Referenced by CommonRights(), EditableDocumentRights(), and EmailRights().