// Auto-generated by mip-sdk-docs-gen/scripts/build_docs.py.
// Populates the version-switcher dropdown in the Microsoft-branded top bar.
(function() {
  var VERSIONS = ["1.18", "1.17", "1.16", "1.15"];
  var CURRENT  = "1.18";
  var HISTORY_URL = "https://learn.microsoft.com/information-protection/develop/version-release-history";

  function render() {
    var menu = document.getElementById("ms-bar-version-menu");
    if (!menu) return;

    // Detect API surface (cpp or c) and the site-root base from the page URL.
    // Path shapes:
    //   /mip-sdk-docs/cpp/index.html                       -> base=/mip-sdk-docs/  api=cpp
    //   /mip-sdk-docs/c/index.html                         -> base=/mip-sdk-docs/  api=c
    //   /mip-sdk-docs/archive/1.17/cpp/index.html          -> base=/mip-sdk-docs/  api=cpp
    var path = window.location.pathname;
    var m = path.match(/^(.*?)(?:archive\/\d+\.\d+\/)?(cpp|c)\//);
    if (!m) return;
    var base = m[1];
    var api  = m[2];

    for (var i = 0; i < VERSIONS.length; i++) {
      var v = VERSIONS[i];
      var a = document.createElement("a");
      a.setAttribute("role", "menuitem");
      if (v === CURRENT) {
        a.href = base + api + "/";
        a.textContent = "v" + v;
        a.className = "current";
      } else {
        a.href = base + "archive/" + v + "/" + api + "/";
        a.textContent = "v" + v;
      }
      menu.appendChild(a);
    }

    var sep = document.createElement("hr");
    menu.appendChild(sep);

    var hist = document.createElement("a");
    hist.href = HISTORY_URL;
    hist.textContent = "Version history →";
    hist.className = "history";
    menu.appendChild(hist);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", render);
  } else {
    render();
  }
})();
