var searchData=
[
  ['networkerror_0',['NetworkError',['../classNetworkError.html',1,'NetworkError'],['../classNetworkError.html#a9765285a5ca3d764ef1fbf1e0a89d914',1,'NetworkError::NetworkError(Category category, const std::string &amp;sanitizedUrl, const std::string &amp;requestId, int32_t statusCode, const std::string &amp;message, const std::string &amp;name=&quot;NetworkError&quot;)'],['../classNetworkError.html#a5d0803034883ae967d1afda9d259439c',1,'NetworkError::NetworkError(Category category, const std::string &amp;sanitizedUrl, const std::string &amp;requestId, int32_t statusCode, const std::string &amp;message, const std::map&lt; std::string, std::string &gt; &amp;debugInfo, const std::map&lt; std::string, std::string &gt; sensitiveDebugInfo, const std::string &amp;name=&quot;NetworkError&quot;)'],['../classNetworkError.html#adf9d3df72055583ade2850e555537400',1,'NetworkError::NetworkError(Category category, int32_t statusCode, const std::string &amp;message, const std::map&lt; std::string, std::string &gt; &amp;debugInfo, const std::map&lt; std::string, std::string &gt; sensitiveDebugInfo, const std::string &amp;name=&quot;NetworkError&quot;)']]],
  ['noauthtokenerror_1',['NoAuthTokenError',['../classNoAuthTokenError.html',1,'NoAuthTokenError'],['../classNoAuthTokenError.html#afc49a73940b5cf4b93eea7e5ada81a13',1,'NoAuthTokenError::NoAuthTokenError(const std::string &amp;message, const std::string &amp;name=&quot;NoAuthTokenError&quot;)'],['../classNoAuthTokenError.html#a9babcc446d2e0182e4bd39388849b9d2',1,'NoAuthTokenError::NoAuthTokenError(const std::string &amp;message, const std::map&lt; std::string, std::string &gt; &amp;debugInfo, const std::map&lt; std::string, std::string &gt; sensitiveDebugInfo, const std::string &amp;name=&quot;NoAuthTokenError&quot;)']]],
  ['noconnection_2',['NoConnection',['../classNetworkError.html#a8cb40eb9f9c590f78170c7552a5bac37a7949462a9c3fc6aa6e0b808c573dc1c4',1,'NetworkError']]],
  ['none_3',['NONE',['../namespacexml.html#a4fb3009600ec5826dc321c46fee9c6c0ab50339a10e1de285ac99d4c3990b8693',1,'xml']]],
  ['nopermissionserror_4',['NoPermissionsError',['../classNoPermissionsError.html',1,'NoPermissionsError'],['../classNoPermissionsError.html#a899dee21788076ba9f3b79734c9da7d8',1,'NoPermissionsError::NoPermissionsError(Category category, const std::string &amp;message, const std::string &amp;referrer=&quot;&quot;, const std::string &amp;owner=&quot;&quot;, const std::string &amp;name=&quot;NoPermissionsError&quot;)'],['../classNoPermissionsError.html#a368592a3770ffeb98000f787af488e0d',1,'NoPermissionsError::NoPermissionsError(Category category, const std::string &amp;message, const std::string &amp;referrer, const std::string &amp;owner, const std::map&lt; std::string, std::string &gt; &amp;debugInfo, const std::map&lt; std::string, std::string &gt; sensitiveDebugInfo, const std::string &amp;name=&quot;NoPermissionsError&quot;)'],['../classNoPermissionsError.html#abdcd3b7122ff3ace0ffc7aaffa9a3041',1,'NoPermissionsError::NoPermissionsError(const std::string &amp;message, const std::string &amp;referrer, const std::string &amp;owner, const std::string &amp;name=&quot;NoPermissionsError&quot;)'],['../classNoPermissionsError.html#ac9bb6f4785635fa874aefba84e964c3b',1,'NoPermissionsError::NoPermissionsError(const std::string &amp;message, const std::string &amp;referrer, const std::string &amp;owner, const std::map&lt; std::string, std::string &gt; &amp;debugInfo, const std::map&lt; std::string, std::string &gt; sensitiveDebugInfo, const std::string &amp;name=&quot;NoPermissionsError&quot;)']]],
  ['nopermissionsextendederror_5',['NoPermissionsExtendedError',['../classNoPermissionsExtendedError.html',1,'NoPermissionsExtendedError'],['../classNoPermissionsExtendedError.html#a0bbf4754985006d81a89ce790fc404d3',1,'NoPermissionsExtendedError::NoPermissionsExtendedError(Category category, const std::string &amp;message, const std::string &amp;referrer, const std::string &amp;owner, const std::vector&lt; ExtendedErrorInfo &gt; &amp;extendedErrorInfo, const std::string &amp;name=GetNoPermissionsExtendedErrorName())'],['../classNoPermissionsExtendedError.html#ab2a0a90c672f928dd5aa2d4ca51aba51',1,'NoPermissionsExtendedError::NoPermissionsExtendedError(Category category, const std::string &amp;message, const std::string &amp;referrer, const std::string &amp;owner, const std::map&lt; std::string, std::string &gt; debugInfo, const std::map&lt; std::string, std::string &gt; sensitiveDebugInfo, const std::vector&lt; ExtendedErrorInfo &gt; &amp;extendedErrorInfo, const std::string &amp;name=GetNoPermissionsExtendedErrorName())']]],
  ['nopolicyerror_6',['NoPolicyError',['../classNoPolicyError.html',1,'NoPolicyError'],['../classNoPolicyError.html#a05deed2517895e7e26fcd5245b79c0a1',1,'NoPolicyError::NoPolicyError(const std::string &amp;message, const Category category, const std::string &amp;name=&quot;NoPolicyError&quot;)'],['../classNoPolicyError.html#acc709ac8422c3926e00ea5ffaab4782b',1,'NoPolicyError::NoPolicyError(const std::string &amp;message, const Category category, const std::map&lt; std::string, std::string &gt; &amp;debugInfo, const std::map&lt; std::string, std::string &gt; sensitiveDebugInfo, const std::string &amp;name=&quot;NoPolicyError&quot;)']]],
  ['notation_7',['NOTATION',['../namespacexml.html#a4fb3009600ec5826dc321c46fee9c6c0aa48419b6a460abbb482d80e4a420643e',1,'xml']]],
  ['notifycommitsuccessful_8',['NotifyCommitSuccessful',['../classFileHandler.html#adb689c03ba38e46190b0a76477f9f33d',1,'FileHandler']]],
  ['notifycommittedactions_9',['NotifyCommittedActions',['../classComputeEngine.html#aac5005d62503dc098d5c6cc67c6afb39',1,'ComputeEngine::NotifyCommittedActions()'],['../classPolicyHandler.html#aa5de9d398d35214b381ebead25046d79',1,'PolicyHandler::NotifyCommittedActions()']]],
  ['notowner_10',['NotOwner',['../classNoPermissionsError.html#a75af81a5a24cda739145edfdb6fa5fb0a7201db7b64ef9ffc729d75e7273453c0',1,'NoPermissionsError']]],
  ['notpremiumlicenseuser_11',['NotPremiumLicenseUser',['../classNoPermissionsError.html#a75af81a5a24cda739145edfdb6fa5fb0ab3b40c088b31a35c92d2604302b6e117',1,'NoPermissionsError']]],
  ['notsupportederror_12',['NotSupportedError',['../classNotSupportedError.html',1,'NotSupportedError'],['../classNotSupportedError.html#a344f08940ba507910224439be3906467',1,'NotSupportedError::NotSupportedError(const std::string &amp;message, const std::string &amp;name=&quot;NotSupportedError&quot;)'],['../classNotSupportedError.html#a14c29c33de592a005c6293045d10fc91',1,'NotSupportedError::NotSupportedError(const std::string &amp;message, const std::map&lt; std::string, std::string &gt; &amp;debugInfo, const std::map&lt; std::string, std::string &gt; sensitiveDebugInfo, const std::string &amp;name=&quot;NotSupportedError&quot;)'],['../classNotSupportedError.html#aa06920b484a10328f0116a0dd1c55840',1,'NotSupportedError::NotSupportedError(const std::string &amp;message, ErrorType errorType, const std::string &amp;name=&quot;NotSupportedError&quot;)']]]
];
