var searchData=
[
  ['message_0',['message',['../structmip__cc__log__message__data.html#ae8692c1ca3d1c78ca25253c6aaa619dd',1,'mip_cc_log_message_data']]],
  ['messagethreadid_1',['messageThreadId',['../structmip__cc__log__message__data.html#ad25b20b86f0c7ef71483045db6a0917d',1,'mip_cc_log_message_data']]],
  ['microsoft_20information_20protection_20sdk_20—_20c_2',['Microsoft Information Protection SDK — C',['../index.html',1,'']]],
  ['millisecondssinceepoch_3',['milliSecondsSinceEpoch',['../structmip__cc__log__message__data.html#abd9267dd55243a47a8f1f3d344353778',1,'mip_cc_log_message_data']]],
  ['mip_5fcc_5fapplication_5faction_5fstate_4',['mip_cc_application_action_state',['../structmip__cc__application__action__state.html',1,'']]],
  ['mip_5fcc_5fapplication_5finfo_5',['mip_cc_application_info',['../structmip__cc__application__info.html',1,'']]],
  ['mip_5fcc_5fasync_5ftask_6',['mip_cc_async_task',['../structmip__cc__async__task.html',1,'']]],
  ['mip_5fcc_5fcreate_5flogger_5fdelegate_5fmessage_5fdata_5fargs_7',['mip_cc_create_logger_delegate_message_data_args',['../structmip__cc__create__logger__delegate__message__data__args.html',1,'']]],
  ['mip_5fcc_5fdocument_5fstate_8',['mip_cc_document_state',['../structmip__cc__document__state.html',1,'']]],
  ['mip_5fcc_5ferror_9',['mip_cc_error',['../structmip__cc__error.html',1,'']]],
  ['mip_5fcc_5ffeature_5foverride_10',['mip_cc_feature_override',['../structmip__cc__feature__override.html',1,'']]],
  ['mip_5fcc_5fguid_11',['mip_cc_guid',['../structmip__cc__guid.html',1,'']]],
  ['mip_5fcc_5fhandle_12',['mip_cc_handle',['../structmip__cc__handle.html',1,'']]],
  ['mip_5fcc_5fhttp_5fheader_13',['mip_cc_http_header',['../structmip__cc__http__header.html',1,'']]],
  ['mip_5fcc_5fhttp_5frequest_14',['mip_cc_http_request',['../structmip__cc__http__request.html',1,'']]],
  ['mip_5fcc_5fhttp_5fresponse_15',['mip_cc_http_response',['../structmip__cc__http__response.html',1,'']]],
  ['mip_5fcc_5fidentity_16',['mip_cc_identity',['../structmip__cc__identity.html',1,'']]],
  ['mip_5fcc_5fkv_5fpair_17',['mip_cc_kv_pair',['../structmip__cc__kv__pair.html',1,'']]],
  ['mip_5fcc_5flog_5fmessage_5fdata_18',['mip_cc_log_message_data',['../structmip__cc__log__message__data.html',1,'']]],
  ['mip_5fcc_5fmetadata_5fentry_19',['mip_cc_metadata_entry',['../structmip__cc__metadata__entry.html',1,'']]],
  ['mip_5fcc_5foauth2_5fchallenge_20',['mip_cc_oauth2_challenge',['../structmip__cc__oauth2__challenge.html',1,'']]],
  ['mip_5fcc_5fuser_5frights_21',['mip_cc_user_rights',['../structmip__cc__user__rights.html',1,'']]],
  ['mip_5fcc_5fuser_5froles_22',['mip_cc_user_roles',['../structmip__cc__user__roles.html',1,'']]]
];
